---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en-US
useGitignore: true

dictionaryDefinitions:
  - name: cspell-words
    path: "./cspell-words.txt"
    addWords: true

dictionaries:
  - cspell-words
  - python
  # - typescript

ignorePaths:
  - ".*"
  - "LICENSE"
  - "cspell.config.yaml"
  # - "requirements.txt"
  - "uv.lock"
